In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

array([0, 1, 2])

In [12]:
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-50]]
iris_y_train = iris_y[indices[:-50]]
iris_X_test = iris_X[indices[-50:]]
iris_y_test = iris_y[indices[-50:]]

In [13]:
#using SVM classification
#using svc model
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
clf=SVC()
iris = datasets.load_iris()
X, y = iris.data, iris.target
clf.fit(X, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [14]:
clf.fit(iris_X_train, iris_y_train)
acc=accuracy_score(iris_y_test, clf.predict(iris_X_test))
print("the accuracy of SVC is "+str(acc*100)+" %")

the accuracy of SVC is 98.0 %


In [15]:
#Nu-Support Vector Classification
from sklearn.svm import NuSVC
from sklearn.metrics import accuracy_score
nuclf=NuSVC()
iris = datasets.load_iris()
X, y = iris.data, iris.target
nuclf.fit(X, y) 

NuSVC(cache_size=200, class_weight=None, coef0=0.0,
   decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
   max_iter=-1, nu=0.5, probability=False, random_state=None,
   shrinking=True, tol=0.001, verbose=False)

In [16]:
nuclf.fit(iris_X_train, iris_y_train)
acc=accuracy_score(iris_y_test, nuclf.predict(iris_X_test))
print("the accuracy of NuSVC is "+str(acc*100)+" %")

the accuracy of NuSVC is 96.0 %


In [19]:
from sklearn.model_selection import cross_val_score#cross-validation
scores = cross_val_score(clf, iris.data, iris.target, cv=5)#check for svc classifier
scores

array([ 0.96666667,  1.        ,  0.96666667,  0.96666667,  1.        ])

In [20]:
scores = cross_val_score(nuclf, iris.data, iris.target, cv=5)#check for Nusvc classifier
scores

array([ 0.96666667,  0.96666667,  0.96666667,  0.93333333,  1.        ])

In [21]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn = KNeighborsClassifier(p=1,n_neighbors=8)#I changed the p to 1 and k=8
scores = cross_val_score(knn, iris.data, iris.target, cv=5)#check for knn classifier
scores

array([ 0.96666667,  0.96666667,  0.93333333,  0.9       ,  1.        ])